name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -c "import sys; import importlib; [importlib.import_module(m) for m in ['telegram','fastapi','pdfplumber','docx','PIL','requests']]; print('Imports OK')"
      - run: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --help
